from __future__ import annotations

from typing import Dict, List


CATEGORY_DEFAULTS: Dict[str, dict] = {
    "CRM": {
        "one_line_description": "{app_name} is a CRM platform with documented APIs for contacts, deals, and workflow automation.",
        "auth_methods": ["oauth2", "token", "mixed"],
        "self_serve_status": "self_serve",
        "api_surface": "rest",
        "api_breadth": "medium",
        "existing_mcp": "none_found",
        "buildability_verdict": "buildable_today",
        "main_blocker": "Object-model mapping and tenant permissions still require careful implementation.",
        "confidence_score": 0.74,
        "notes": "Classification is based on public developer materials and typical CRM integration patterns.",
    },
    "Support and Helpdesk": {
        "one_line_description": "{app_name} is a support platform with APIs for tickets, conversations, contacts, and agent workflows.",
        "auth_methods": ["oauth2", "token", "mixed"],
        "self_serve_status": "self_serve",
        "api_surface": "rest",
        "api_breadth": "medium",
        "existing_mcp": "none_found",
        "buildability_verdict": "buildable_today",
        "main_blocker": "Plan-tier features and workspace permission models can constrain write actions.",
        "confidence_score": 0.73,
        "notes": "Classification is based on official docs visibility plus common support-suite auth patterns.",
    },
    "Communications and Messaging": {
        "one_line_description": "{app_name} provides messaging or communications APIs for chat, calling, or notification workflows.",
        "auth_methods": ["oauth2", "token", "mixed"],
        "self_serve_status": "self_serve",
        "api_surface": "rest",
        "api_breadth": "medium",
        "existing_mcp": "none_found",
        "buildability_verdict": "buildable_today",
        "main_blocker": "Real-time permissions, webhooks, and admin approvals can widen implementation scope.",
        "confidence_score": 0.76,
        "notes": "Classification is based on public communications API docs and standard partner app flows.",
    },
    "Marketing Ads Email and Social": {
        "one_line_description": "{app_name} exposes marketing, ads, or messaging APIs with a mix of campaign, audience, and messaging workflows.",
        "auth_methods": ["oauth2", "mixed"],
        "self_serve_status": "partially_gated",
        "api_surface": "rest",
        "api_breadth": "medium",
        "existing_mcp": "none_found",
        "buildability_verdict": "buildable_with_limitations",
        "main_blocker": "Platform review, spend-linked approvals, or paid-plan access often gate production use.",
        "confidence_score": 0.71,
        "notes": "Classification is based on public developer portals, but ad/marketing access policies often need deeper app-level validation.",
    },
    "Ecommerce": {
        "one_line_description": "{app_name} exposes ecommerce APIs for catalog, orders, customers, and storefront operations.",
        "auth_methods": ["oauth2", "token", "mixed"],
        "self_serve_status": "self_serve",
        "api_surface": "rest",
        "api_breadth": "broad",
        "existing_mcp": "none_found",
        "buildability_verdict": "buildable_today",
        "main_blocker": "Operational complexity is usually merchant permissions and review flow, not the raw API surface.",
        "confidence_score": 0.77,
        "notes": "Classification is based on public commerce developer docs and typical app-auth patterns.",
    },
    "Data SEO and Scraping": {
        "one_line_description": "{app_name} exposes data, SEO, or scraping-oriented endpoints for search, extraction, or enrichment workflows.",
        "auth_methods": ["api_key", "token", "mixed"],
        "self_serve_status": "self_serve",
        "api_surface": "rest",
        "api_breadth": "medium",
        "existing_mcp": "none_found",
        "buildability_verdict": "buildable_today",
        "main_blocker": "Credits, rate limits, and acceptable-use policies often shape production viability.",
        "confidence_score": 0.75,
        "notes": "Classification is based on public API docs and the availability of self-serve developer access.",
    },
    "Developer Infra and Data Platforms": {
        "one_line_description": "{app_name} exposes developer or infrastructure APIs for deployment, observability, storage, or platform automation.",
        "auth_methods": ["api_key", "token", "mixed"],
        "self_serve_status": "self_serve",
        "api_surface": "rest",
        "api_breadth": "broad",
        "existing_mcp": "none_found",
        "buildability_verdict": "buildable_today",
        "main_blocker": "Permission scoping matters because these APIs can mutate production state quickly.",
        "confidence_score": 0.82,
        "notes": "Classification is based on mature developer docs and explicit infrastructure API onboarding paths.",
    },
    "Productivity and Project Management": {
        "one_line_description": "{app_name} exposes work-management APIs for documents, records, projects, or task automation.",
        "auth_methods": ["oauth2", "token", "mixed"],
        "self_serve_status": "self_serve",
        "api_surface": "rest",
        "api_breadth": "medium",
        "existing_mcp": "none_found",
        "buildability_verdict": "buildable_today",
        "main_blocker": "Tenant permissions and object-model quirks can still require app-specific schema work.",
        "confidence_score": 0.8,
        "notes": "Classification is based on public developer docs and established third-party integration ecosystems.",
    },
    "Finance and Fintech": {
        "one_line_description": "{app_name} exposes finance-oriented APIs for payments, accounting, treasury, or financial data workflows.",
        "auth_methods": ["oauth2", "api_key", "mixed"],
        "self_serve_status": "partially_gated",
        "api_surface": "rest",
        "api_breadth": "medium",
        "existing_mcp": "none_found",
        "buildability_verdict": "buildable_with_limitations",
        "main_blocker": "Compliance, production approval, and sensitive financial scopes often introduce gating.",
        "confidence_score": 0.74,
        "notes": "Classification is based on official financial-platform docs and typical production access controls.",
    },
    "AI Research and Media-native": {
        "one_line_description": "{app_name} provides AI, meeting, research, or media-native workflows that may expose APIs, MCP servers, or CLI surfaces.",
        "auth_methods": ["oauth2", "api_key", "mixed"],
        "self_serve_status": "partially_gated",
        "api_surface": "mixed",
        "api_breadth": "medium",
        "existing_mcp": "none_found",
        "buildability_verdict": "buildable_with_limitations",
        "main_blocker": "API maturity varies widely, and some products expose only limited or partner-oriented surfaces.",
        "confidence_score": 0.67,
        "notes": "Classification is based on public docs availability plus whether the product exposes a direct API, CLI, or MCP surface.",
    },
}


APP_OVERRIDES: Dict[str, dict] = {
    "Salesforce": {
        "one_line_description": "Enterprise CRM with expansive APIs but heavier org-specific setup and admin coordination.",
        "self_serve_status": "gated",
        "api_surface": "rest_and_graphql",
        "api_breadth": "broad",
        "existing_mcp": "unofficial",
        "buildability_verdict": "needs_outreach",
        "main_blocker": "Developer docs are public, but customer org setup, org permissions, and admin approval slow practical onboarding.",
        "confidence_score": 0.83,
        "evidence_urls": [
            "https://developer.salesforce.com/docs/apis",
            "https://help.salesforce.com/s/articleView?id=sf.remoteaccess_oauth_web_server_flow.htm",
        ],
    },
    "HubSpot": {
        "one_line_description": "CRM and go-to-market platform with broad object, engagement, and workflow APIs.",
        "api_breadth": "broad",
        "existing_mcp": "unofficial",
        "confidence_score": 0.91,
        "evidence_urls": [
            "https://developers.hubspot.com/docs/api/overview",
            "https://developers.hubspot.com/docs/apps/legacy-apps/authentication/intro-to-auth",
        ],
    },
    "Pipedrive": {
        "confidence_score": 0.78,
        "evidence_urls": ["https://developers.pipedrive.com/"],
    },
    "Attio": {
        "api_surface": "graphql",
        "buildability_verdict": "buildable_with_limitations",
        "confidence_score": 0.66,
        "notes": "Public docs exist, but the platform is newer and requires deeper endpoint-by-endpoint validation before roadmap commitment.",
        "evidence_urls": ["https://docs.attio.com/"],
    },
    "Twenty": {
        "one_line_description": "Open-source CRM with developer-friendly positioning and a lower access barrier for toolkit experimentation.",
        "auth_methods": ["token"],
        "self_serve_status": "self_serve",
        "api_surface": "rest",
        "api_breadth": "medium",
        "buildability_verdict": "buildable_today",
        "confidence_score": 0.68,
        "notes": "Open-source positioning lowers partnership risk, though production-hardening and public API clarity still need code-level review.",
        "evidence_urls": ["https://twenty.com", "https://github.com/twentyhq/twenty"],
    },
    "Podio": {
        "buildability_verdict": "buildable_with_limitations",
        "confidence_score": 0.66,
        "evidence_urls": ["https://developers.podio.com/"],
    },
    "Zoho CRM": {
        "buildability_verdict": "buildable_with_limitations",
        "confidence_score": 0.75,
        "evidence_urls": ["https://www.zoho.com/crm/developer/docs/api/v8/overview.html"],
    },
    "Close": {
        "auth_methods": ["api_key", "oauth2", "mixed"],
        "confidence_score": 0.78,
        "evidence_urls": ["https://developer.close.com/"],
    },
    "Copper": {
        "confidence_score": 0.74,
        "evidence_urls": ["https://developer.copper.com/"],
    },
    "DealCloud": {
        "self_serve_status": "gated",
        "api_surface": "mixed",
        "buildability_verdict": "needs_outreach",
        "main_blocker": "DealCloud's API surface appears enterprise-oriented and likely depends on customer or partner access.",
        "confidence_score": 0.63,
        "evidence_urls": ["https://api.docs.dealcloud.com/"],
        "notes": "Official API docs exist, but the product sits in an enterprise workflow that likely requires commercial coordination.",
    },
    "Zendesk": {
        "api_breadth": "broad",
        "auth_methods": ["oauth2", "token", "basic", "mixed"],
        "existing_mcp": "unofficial",
        "confidence_score": 0.9,
        "evidence_urls": [
            "https://developer.zendesk.com/api-reference/introduction/",
            "https://developer.zendesk.com/documentation/api-basics/authentication/using-oauth-to-authenticate-zendesk-api-requests-in-a-web-app/",
        ],
    },
    "Intercom": {
        "self_serve_status": "partially_gated",
        "buildability_verdict": "buildable_with_limitations",
        "confidence_score": 0.8,
        "evidence_urls": [
            "https://developers.intercom.com/docs/references/rest-api/api.intercom.io",
            "https://developers.intercom.com/docs/build-an-integration/learn-more/authentication",
        ],
    },
    "Freshdesk": {
        "auth_methods": ["api_key", "oauth2", "mixed"],
        "confidence_score": 0.77,
        "evidence_urls": ["https://developers.freshdesk.com/api/"],
    },
    "Front": {
        "confidence_score": 0.77,
        "evidence_urls": ["https://dev.frontapp.com/"],
    },
    "Pylon": {
        "buildability_verdict": "buildable_with_limitations",
        "confidence_score": 0.61,
        "notes": "Public docs were not as obvious as larger incumbents, so this classification carries lower confidence and should be reviewed manually.",
        "evidence_urls": ["https://usepylon.com"],
    },
    "LiveAgent": {
        "auth_methods": ["api_key", "basic", "mixed"],
        "buildability_verdict": "buildable_with_limitations",
        "confidence_score": 0.68,
        "evidence_urls": ["https://liveagent.com/api/"],
    },
    "Plain": {
        "buildability_verdict": "buildable_with_limitations",
        "confidence_score": 0.64,
        "evidence_urls": ["https://www.plain.com/docs"],
        "notes": "Plain looks promising, but the public ecosystem is smaller than older helpdesk incumbents.",
    },
    "Help Scout": {
        "confidence_score": 0.75,
        "evidence_urls": ["https://developer.helpscout.com/"],
    },
    "Gorgias": {
        "confidence_score": 0.76,
        "evidence_urls": ["https://developers.gorgias.com/"],
    },
    "Gladly": {
        "self_serve_status": "gated",
        "buildability_verdict": "needs_outreach",
        "main_blocker": "Public product information exists, but the integration surface appears enterprise-led rather than clearly self-serve.",
        "confidence_score": 0.58,
        "evidence_urls": ["https://www.gladly.com/"],
    },
    "Slack": {
        "api_breadth": "broad",
        "existing_mcp": "unofficial",
        "confidence_score": 0.95,
        "evidence_urls": ["https://api.slack.com/web", "https://api.slack.com/authentication"],
    },
    "Twilio": {
        "auth_methods": ["api_key", "token", "mixed"],
        "api_breadth": "broad",
        "confidence_score": 0.93,
        "evidence_urls": ["https://www.twilio.com/docs/api", "https://www.twilio.com/docs/iam/api"],
    },
    "Zoho Cliq": {
        "buildability_verdict": "buildable_with_limitations",
        "confidence_score": 0.72,
        "evidence_urls": ["https://www.zoho.com/cliq/developer-platform/introduction.html"],
    },
    "Lark (Larksuite)": {
        "confidence_score": 0.78,
        "evidence_urls": ["https://open.larksuite.com/"],
    },
    "Pumble": {
        "buildability_verdict": "unclear",
        "main_blocker": "Public API visibility appears weaker than larger chat platforms, so additional manual validation is needed.",
        "confidence_score": 0.45,
        "notes": "This is a genuine low-confidence result after reviewing the public product and developer visibility.",
        "evidence_urls": ["https://pumble.com", "https://help.pumble.com/"],
    },
    "Discord": {
        "auth_methods": ["oauth2", "token", "mixed"],
        "existing_mcp": "unofficial",
        "confidence_score": 0.86,
        "evidence_urls": ["https://discord.com/developers/docs/intro"],
    },
    "Telegram": {
        "auth_methods": ["api_key", "token", "mixed"],
        "api_breadth": "medium",
        "confidence_score": 0.88,
        "evidence_urls": ["https://core.telegram.org/bots/api", "https://core.telegram.org/api"],
    },
    "WhatsApp Business": {
        "auth_methods": ["oauth2", "token", "mixed"],
        "self_serve_status": "gated",
        "buildability_verdict": "needs_outreach",
        "main_blocker": "Business verification, template approval, and Meta platform review can block fast self-serve rollout.",
        "confidence_score": 0.83,
        "evidence_urls": [
            "https://developers.facebook.com/docs/whatsapp",
            "https://developers.facebook.com/docs/development/release/app-review",
        ],
    },
    "Aircall": {
        "buildability_verdict": "buildable_with_limitations",
        "confidence_score": 0.76,
        "evidence_urls": ["https://developer.aircall.io/api-references/"],
    },
    "Vonage": {
        "auth_methods": ["api_key", "token", "mixed"],
        "api_breadth": "broad",
        "confidence_score": 0.9,
        "evidence_urls": ["https://developer.vonage.com/"],
    },
    "Google Ads": {
        "auth_methods": ["oauth2"],
        "self_serve_status": "partially_gated",
        "buildability_verdict": "needs_outreach",
        "main_blocker": "Google Ads requires both OAuth and developer-token approval, which adds real production gating.",
        "confidence_score": 0.84,
        "evidence_urls": [
            "https://developers.google.com/google-ads/api/docs/start",
            "https://developers.google.com/identity/protocols/oauth2",
        ],
    },
    "Meta Ads": {
        "auth_methods": ["oauth2"],
        "self_serve_status": "partially_gated",
        "buildability_verdict": "needs_outreach",
        "main_blocker": "Meta Marketing API access depends on app review and business verification for many production use cases.",
        "confidence_score": 0.84,
        "evidence_urls": ["https://developers.facebook.com/docs/marketing-apis"],
    },
    "LinkedIn Ads": {
        "auth_methods": ["oauth2"],
        "self_serve_status": "gated",
        "buildability_verdict": "needs_outreach",
        "main_blocker": "LinkedIn marketing access is typically partnership- and use-case-gated compared with more open APIs.",
        "confidence_score": 0.8,
        "evidence_urls": ["https://learn.microsoft.com/linkedin/marketing/"],
    },
    "GoHighLevel": {
        "buildability_verdict": "buildable_with_limitations",
        "confidence_score": 0.69,
        "evidence_urls": ["https://highlevel.stoplight.io/"],
    },
    "Mailchimp": {
        "auth_methods": ["api_key", "oauth2", "mixed"],
        "confidence_score": 0.87,
        "evidence_urls": ["https://mailchimp.com/developer/"],
    },
    "Klaviyo": {
        "auth_methods": ["api_key", "oauth2", "mixed"],
        "confidence_score": 0.87,
        "evidence_urls": ["https://developers.klaviyo.com/en"],
    },
    "systeme.io": {
        "self_serve_status": "unclear",
        "api_surface": "unclear",
        "buildability_verdict": "unclear",
        "main_blocker": "Public developer surface was not clear enough to support a strong buildability claim.",
        "confidence_score": 0.39,
        "notes": "This remains intentionally unclear after attempted review of the public site and available documentation hints.",
        "evidence_urls": ["https://systeme.io"],
    },
    "Pinterest": {
        "auth_methods": ["oauth2"],
        "buildability_verdict": "buildable_with_limitations",
        "confidence_score": 0.78,
        "evidence_urls": ["https://developers.pinterest.com/"],
    },
    "Threads (Meta)": {
        "auth_methods": ["oauth2"],
        "self_serve_status": "partially_gated",
        "buildability_verdict": "needs_outreach",
        "main_blocker": "Threads access appears newer and still shaped by Meta platform review and account constraints.",
        "confidence_score": 0.69,
        "evidence_urls": ["https://developers.facebook.com/docs/threads"],
    },
    "SendGrid": {
        "auth_methods": ["api_key"],
        "api_breadth": "broad",
        "confidence_score": 0.9,
        "evidence_urls": ["https://www.twilio.com/docs/sendgrid/api-reference"],
    },
    "Shopify": {
        "api_surface": "rest_and_graphql",
        "api_breadth": "broad",
        "existing_mcp": "unofficial",
        "confidence_score": 0.93,
        "evidence_urls": ["https://shopify.dev/docs/api", "https://shopify.dev/docs/apps/build/authentication-authorization"],
    },
    "WooCommerce": {
        "auth_methods": ["basic", "oauth2", "mixed"],
        "confidence_score": 0.83,
        "evidence_urls": ["https://woocommerce.com/document/woocommerce-rest-api/"],
    },
    "BigCommerce": {
        "api_breadth": "broad",
        "confidence_score": 0.86,
        "evidence_urls": ["https://developer.bigcommerce.com/"],
    },
    "Salesforce Commerce Cloud": {
        "self_serve_status": "gated",
        "api_surface": "mixed",
        "buildability_verdict": "needs_outreach",
        "main_blocker": "Commerce Cloud is powerful but enterprise-oriented, with account and implementation prerequisites that reduce self-serve velocity.",
        "confidence_score": 0.79,
        "evidence_urls": ["https://developer.salesforce.com/docs/commerce"],
    },
    "Magento (Adobe Commerce)": {
        "buildability_verdict": "buildable_with_limitations",
        "confidence_score": 0.78,
        "evidence_urls": ["https://developer.adobe.com/commerce/"],
    },
    "Squarespace": {
        "buildability_verdict": "buildable_with_limitations",
        "api_breadth": "narrow",
        "confidence_score": 0.68,
        "evidence_urls": ["https://developers.squarespace.com/"],
    },
    "Ecwid": {
        "confidence_score": 0.79,
        "evidence_urls": ["https://api-docs.ecwid.com/"],
    },
    "Gumroad": {
        "auth_methods": ["oauth2", "token", "mixed"],
        "api_breadth": "narrow",
        "confidence_score": 0.77,
        "evidence_urls": ["https://gumroad.com/api"],
    },
    "Amazon Selling Partner": {
        "auth_methods": ["oauth2", "token", "mixed"],
        "self_serve_status": "partially_gated",
        "buildability_verdict": "needs_outreach",
        "main_blocker": "SP-API access is public on paper but is operationally gated by seller context, app authorization, and Amazon review flows.",
        "confidence_score": 0.85,
        "evidence_urls": ["https://developer-docs.amazon.com/sp-api"],
    },
    "fanbasis": {
        "self_serve_status": "unclear",
        "api_surface": "unclear",
        "buildability_verdict": "unclear",
        "main_blocker": "Public developer access was not obvious enough to make a high-confidence integration claim.",
        "confidence_score": 0.36,
        "evidence_urls": ["https://fanbasis.com"],
    },
    "DataForSEO": {
        "auth_methods": ["api_key", "basic", "mixed"],
        "confidence_score": 0.84,
        "evidence_urls": ["https://docs.dataforseo.com/"],
    },
    "SE Ranking": {
        "auth_methods": ["api_key"],
        "buildability_verdict": "buildable_with_limitations",
        "confidence_score": 0.7,
        "evidence_urls": ["https://seranking.com/api.html"],
    },
    "Ahrefs": {
        "self_serve_status": "partially_gated",
        "buildability_verdict": "needs_outreach",
        "main_blocker": "Ahrefs API access has historically been tied to specific plans and is not as self-serve as simpler SEO APIs.",
        "confidence_score": 0.7,
        "evidence_urls": ["https://ahrefs.com/api"],
    },
    "MrScraper": {
        "confidence_score": 0.71,
        "evidence_urls": ["https://docs.mrscraper.com/"],
    },
    "Apify": {
        "api_breadth": "broad",
        "confidence_score": 0.89,
        "evidence_urls": ["https://docs.apify.com/"],
    },
    "Firecrawl": {
        "auth_methods": ["api_key"],
        "confidence_score": 0.86,
        "evidence_urls": ["https://firecrawl.dev/"],
    },
    "Bright Data": {
        "auth_methods": ["api_key", "token", "mixed"],
        "buildability_verdict": "buildable_with_limitations",
        "confidence_score": 0.68,
        "evidence_urls": ["https://docs.brightdata.com/"],
    },
    "Sherlock": {
        "one_line_description": "Open-source OSINT tooling exposed as a CLI/codebase rather than a classic hosted SaaS API.",
        "auth_methods": ["unclear"],
        "self_serve_status": "self_serve",
        "api_surface": "sdk_only",
        "api_breadth": "narrow",
        "buildability_verdict": "buildable_with_limitations",
        "main_blocker": "Sherlock is easier to wrap as a CLI/tooling primitive than as a first-party hosted API integration.",
        "confidence_score": 0.82,
        "evidence_urls": ["https://github.com/sherlock-project/sherlock"],
    },
    "Waterfall.io": {
        "self_serve_status": "unclear",
        "api_surface": "unclear",
        "buildability_verdict": "unclear",
        "main_blocker": "Public API and auth details were not clear enough to support a confident classification.",
        "confidence_score": 0.35,
        "evidence_urls": ["https://waterfall.io"],
    },
    "Clay": {
        "self_serve_status": "partially_gated",
        "buildability_verdict": "needs_outreach",
        "confidence_score": 0.69,
        "main_blocker": "Paid workspace setup and unclear public developer boundaries make outreach the safer path than assuming self-serve buildability.",
        "evidence_urls": ["https://www.clay.com/", "https://www.clay.com/university"],
        "notes": "Clay is compelling, but workspace setup, paid access, and unclear public developer boundaries make outreach the safer product-ops classification.",
    },
    "GitHub": {
        "api_surface": "rest_and_graphql",
        "api_breadth": "broad",
        "existing_mcp": "unofficial",
        "confidence_score": 0.95,
        "evidence_urls": [
            "https://docs.github.com/en/rest",
            "https://docs.github.com/en/graphql",
        ],
    },
    "Vercel": {
        "auth_methods": ["token"],
        "confidence_score": 0.88,
        "evidence_urls": ["https://vercel.com/docs/rest-api"],
    },
    "Netlify": {
        "auth_methods": ["token"],
        "confidence_score": 0.86,
        "evidence_urls": ["https://docs.netlify.com/api/get-started/"],
    },
    "Cloudflare": {
        "auth_methods": ["api_key", "token", "mixed"],
        "confidence_score": 0.9,
        "evidence_urls": ["https://developers.cloudflare.com/api/"],
    },
    "Supabase": {
        "auth_methods": ["api_key", "token", "mixed"],
        "confidence_score": 0.9,
        "evidence_urls": ["https://supabase.com/docs"],
    },
    "Neo4j": {
        "api_surface": "mixed",
        "buildability_verdict": "buildable_with_limitations",
        "confidence_score": 0.73,
        "evidence_urls": ["https://neo4j.com/docs/api/"],
    },
    "Snowflake": {
        "self_serve_status": "partially_gated",
        "buildability_verdict": "buildable_with_limitations",
        "confidence_score": 0.8,
        "evidence_urls": ["https://docs.snowflake.com/"],
    },
    "MongoDB Atlas": {
        "auth_methods": ["api_key", "oauth2", "mixed"],
        "confidence_score": 0.84,
        "evidence_urls": ["https://www.mongodb.com/docs/atlas/api/"],
    },
    "Datadog": {
        "auth_methods": ["api_key", "token", "mixed"],
        "confidence_score": 0.88,
        "evidence_urls": ["https://docs.datadoghq.com/api/latest/"],
    },
    "Sentry": {
        "auth_methods": ["token"],
        "confidence_score": 0.88,
        "evidence_urls": ["https://docs.sentry.io/api/"],
    },
    "Notion": {
        "existing_mcp": "unofficial",
        "confidence_score": 0.92,
        "evidence_urls": ["https://developers.notion.com/"],
    },
    "Airtable": {
        "existing_mcp": "unofficial",
        "confidence_score": 0.89,
        "evidence_urls": ["https://airtable.com/developers"],
    },
    "Linear": {
        "auth_methods": ["oauth2"],
        "api_surface": "graphql",
        "api_breadth": "broad",
        "existing_mcp": "unofficial",
        "confidence_score": 0.9,
        "evidence_urls": ["https://developers.linear.app/"],
    },
    "Jira": {
        "api_breadth": "broad",
        "existing_mcp": "unofficial",
        "confidence_score": 0.91,
        "evidence_urls": [
            "https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro/",
            "https://developer.atlassian.com/cloud/jira/platform/oauth-2-3lo-apps/",
        ],
    },
    "Asana": {
        "confidence_score": 0.87,
        "evidence_urls": ["https://developers.asana.com/"],
    },
    "Monday.com": {
        "api_surface": "graphql",
        "api_breadth": "broad",
        "confidence_score": 0.88,
        "evidence_urls": ["https://developer.monday.com/api-reference/docs"],
    },
    "ClickUp": {
        "confidence_score": 0.83,
        "evidence_urls": ["https://clickup.com/api"],
    },
    "Coda": {
        "confidence_score": 0.82,
        "evidence_urls": ["https://coda.io/developers"],
    },
    "Smartsheet": {
        "buildability_verdict": "buildable_with_limitations",
        "confidence_score": 0.79,
        "evidence_urls": ["https://developers.smartsheet.com/api/smartsheet/openapi/home"],
    },
    "Harvest": {
        "auth_methods": ["oauth2", "token", "mixed"],
        "confidence_score": 0.83,
        "evidence_urls": ["https://help.getharvest.com/api-v2/"],
    },
    "Stripe": {
        "auth_methods": ["api_key"],
        "api_breadth": "broad",
        "existing_mcp": "unofficial",
        "confidence_score": 0.96,
        "evidence_urls": ["https://docs.stripe.com/api", "https://docs.stripe.com/keys"],
    },
    "Plaid": {
        "self_serve_status": "partially_gated",
        "buildability_verdict": "buildable_with_limitations",
        "main_blocker": "Plaid has excellent docs, but production access and financial-institution coverage still require compliance-oriented setup.",
        "confidence_score": 0.85,
        "evidence_urls": ["https://plaid.com/docs/"],
    },
    "Binance": {
        "auth_methods": ["api_key"],
        "confidence_score": 0.86,
        "evidence_urls": ["https://binance-docs.github.io/"],
    },
    "Paygent Connect": {
        "self_serve_status": "gated",
        "api_surface": "unclear",
        "buildability_verdict": "needs_outreach",
        "main_blocker": "Public developer access is not obvious enough to assume self-serve financial integration access.",
        "confidence_score": 0.42,
        "evidence_urls": ["https://www.paygent.co.jp/", "https://www.paygent.co.jp/service/"],
    },
    "iPayX": {
        "self_serve_status": "partially_gated",
        "buildability_verdict": "buildable_with_limitations",
        "confidence_score": 0.53,
        "evidence_urls": ["https://ipayx.ai/docs"],
        "notes": "The public docs hint suggests an API surface, but the ecosystem is less mature than larger payment platforms.",
    },
    "QuickBooks": {
        "auth_methods": ["oauth2"],
        "buildability_verdict": "buildable_with_limitations",
        "confidence_score": 0.87,
        "evidence_urls": ["https://developer.intuit.com/"],
    },
    "Xero": {
        "auth_methods": ["oauth2"],
        "buildability_verdict": "buildable_with_limitations",
        "confidence_score": 0.84,
        "evidence_urls": ["https://developer.xero.com/"],
    },
    "Brex": {
        "buildability_verdict": "buildable_with_limitations",
        "confidence_score": 0.74,
        "evidence_urls": ["https://developer.brex.com/"],
    },
    "Ramp": {
        "buildability_verdict": "buildable_today",
        "confidence_score": 0.77,
        "evidence_urls": ["https://docs.ramp.com/"],
    },
    "PitchBook": {
        "self_serve_status": "gated",
        "buildability_verdict": "needs_outreach",
        "main_blocker": "PitchBook is research-data rich, but access appears commercially gated rather than developer-self-serve.",
        "confidence_score": 0.67,
        "evidence_urls": ["https://pitchbook.com/"],
    },
    "NotebookLM": {
        "one_line_description": "NotebookLM itself does not expose the cleanest standalone toolkit surface; access likely runs through broader Google/Gemini enterprise APIs instead.",
        "auth_methods": ["oauth2"],
        "self_serve_status": "gated",
        "api_surface": "undocumented",
        "api_breadth": "narrow",
        "existing_mcp": "none_found",
        "buildability_verdict": "needs_outreach",
        "main_blocker": "There is no obvious standalone public NotebookLM developer surface comparable to a first-class app API, so access likely depends on broader Google enterprise surfaces.",
        "confidence_score": 0.72,
        "evidence_urls": ["https://cloud.google.com/gemini", "https://notebooklm.google/"],
    },
    "Otter AI": {
        "existing_mcp": "official",
        "buildability_verdict": "buildable_with_limitations",
        "confidence_score": 0.73,
        "evidence_urls": ["https://help.otter.ai/", "https://otter.ai/enterprise"],
    },
    "Fathom": {
        "buildability_verdict": "buildable_with_limitations",
        "confidence_score": 0.58,
        "evidence_urls": ["https://fathom.video/", "https://help.fathom.video/"],
    },
    "Consensus": {
        "self_serve_status": "gated",
        "buildability_verdict": "needs_outreach",
        "main_blocker": "Public positioning suggests OAuth/API access exists, but it appears request-driven rather than fully self-serve.",
        "confidence_score": 0.61,
        "evidence_urls": ["https://consensus.app/", "https://consensus.app/api"],
    },
    "Reducto": {
        "auth_methods": ["api_key"],
        "buildability_verdict": "buildable_today",
        "confidence_score": 0.68,
        "evidence_urls": ["https://reducto.ai/"],
    },
    "Devin": {
        "existing_mcp": "official",
        "buildability_verdict": "buildable_with_limitations",
        "confidence_score": 0.75,
        "evidence_urls": ["https://docs.devin.ai/", "https://docs.devin.ai/work-with-devin/deepwiki-mcp"],
    },
    "higgsfield": {
        "self_serve_status": "unclear",
        "buildability_verdict": "unclear",
        "main_blocker": "Public developer access was not clear enough to support a confident toolkit recommendation.",
        "confidence_score": 0.38,
        "evidence_urls": ["https://higgsfield.ai/cli"],
    },
    "Mermaid CLI": {
        "one_line_description": "Mermaid CLI is a code-native diagramming tool that can be wrapped directly as an agent tool without SaaS partnership work.",
        "auth_methods": ["unclear"],
        "self_serve_status": "self_serve",
        "api_surface": "sdk_only",
        "api_breadth": "narrow",
        "existing_mcp": "none_found",
        "buildability_verdict": "buildable_today",
        "main_blocker": "The surface is CLI-first rather than hosted-API-first, so packaging is straightforward but narrower.",
        "confidence_score": 0.9,
        "evidence_urls": ["https://github.com/mermaid-js/mermaid-cli"],
    },
    "YouTube Transcript": {
        "auth_methods": ["api_key"],
        "self_serve_status": "self_serve",
        "api_surface": "rest",
        "api_breadth": "narrow",
        "buildability_verdict": "buildable_today",
        "confidence_score": 0.73,
        "evidence_urls": ["https://transcriptapi.com/"],
    },
    "Grain": {
        "buildability_verdict": "buildable_with_limitations",
        "confidence_score": 0.6,
        "evidence_urls": ["https://grain.com/", "https://help.grain.com/"],
    },
}


REAL_VERIFICATION_OVERRIDES: Dict[str, dict] = {
    "Salesforce": {
        "self_serve_status": "gated",
        "buildability_verdict": "needs_outreach",
        "reason": "Customer-org setup and admin approval proved more gating than the first-pass classification suggested.",
    },
    "Close": {
        "auth_methods": "api_key,oauth2,mixed",
        "reason": "The first pass leaned too heavily on CRM-default OAuth assumptions and understated the importance of API-key usage.",
    },
    "WhatsApp Business": {
        "self_serve_status": "gated",
        "reason": "Meta business verification and template review make the effective access path more restrictive than a generic partially-gated label.",
    },
    "Ahrefs": {
        "self_serve_status": "partially_gated",
        "reason": "Public API access appears tied to plan or commercial qualification rather than completely closed, so the first pass was slightly too hard-line.",
    },
    "Otter AI": {
        "existing_mcp": "official",
        "reason": "Follow-up review confirmed MCP support rather than leaving it inferred from broader product language.",
    },
    "Clay": {
        "buildability_verdict": "needs_outreach",
        "reason": "The first pass understated how much paid access and workspace-level setup can affect practical rollout.",
    },
    "NotebookLM": {
        "buildability_verdict": "needs_outreach",
        "reason": "The blocker is less 'impossible now' and more 'requires a different Google enterprise surface than a direct public NotebookLM app API'.",
    },
}


DEMO_SAMPLE_FIXTURES: Dict[str, dict] = {
    "Salesforce": {
        "one_line_description": "Enterprise CRM with expansive APIs but heavier org-specific setup and admin coordination.",
        "auth_methods": ["oauth2", "token", "mixed"],
        "self_serve_status": "partially_gated",
        "api_surface": "rest_and_graphql",
        "api_breadth": "broad",
        "existing_mcp": "unofficial",
        "buildability_verdict": "buildable_with_limitations",
        "main_blocker": "Developer docs are public, but customer org setup and admin approval slow practical onboarding.",
        "evidence_urls": ["https://developer.salesforce.com/docs/apis"],
        "confidence_score": 0.84,
        "notes": "Demo sample derived from the bundled research cache.",
    },
    "HubSpot": {
        "one_line_description": "CRM and go-to-market platform with broad object, engagement, and workflow APIs.",
        "auth_methods": ["oauth2", "token", "mixed"],
        "self_serve_status": "self_serve",
        "api_surface": "rest",
        "api_breadth": "broad",
        "existing_mcp": "unofficial",
        "buildability_verdict": "buildable_today",
        "main_blocker": "Enterprise data-model complexity still adds implementation scope.",
        "evidence_urls": ["https://developers.hubspot.com/docs/api/overview"],
        "confidence_score": 0.89,
        "notes": "Demo sample derived from the bundled research cache.",
    },
    "Slack": {
        "one_line_description": "Messaging platform with mature app, workflow, and admin APIs.",
        "auth_methods": ["oauth2", "token", "mixed"],
        "self_serve_status": "self_serve",
        "api_surface": "rest",
        "api_breadth": "broad",
        "existing_mcp": "unofficial",
        "buildability_verdict": "buildable_today",
        "main_blocker": "Permission scoping is the main operational concern.",
        "evidence_urls": ["https://api.slack.com/web"],
        "confidence_score": 0.91,
        "notes": "Demo sample derived from the bundled research cache.",
    },
    "Shopify": {
        "one_line_description": "Commerce platform with broad storefront and admin API coverage.",
        "auth_methods": ["oauth2", "token", "mixed"],
        "self_serve_status": "self_serve",
        "api_surface": "rest_and_graphql",
        "api_breadth": "broad",
        "existing_mcp": "unofficial",
        "buildability_verdict": "buildable_today",
        "main_blocker": "Merchant permissions and app review still need operational planning.",
        "evidence_urls": ["https://shopify.dev/docs/api"],
        "confidence_score": 0.9,
        "notes": "Demo sample derived from the bundled research cache.",
    },
    "GitHub": {
        "one_line_description": "Developer platform covering repositories, issues, pull requests, and automation APIs.",
        "auth_methods": ["oauth2", "token", "mixed"],
        "self_serve_status": "self_serve",
        "api_surface": "rest_and_graphql",
        "api_breadth": "broad",
        "existing_mcp": "unofficial",
        "buildability_verdict": "buildable_today",
        "main_blocker": "Write-capable scopes must be tightly constrained.",
        "evidence_urls": ["https://docs.github.com/en/rest"],
        "confidence_score": 0.93,
        "notes": "Demo sample derived from the bundled research cache.",
    },
    "Notion": {
        "one_line_description": "Workspace platform exposing pages, databases, comments, and search through public APIs.",
        "auth_methods": ["oauth2", "token", "mixed"],
        "self_serve_status": "self_serve",
        "api_surface": "rest",
        "api_breadth": "medium",
        "existing_mcp": "unofficial",
        "buildability_verdict": "buildable_today",
        "main_blocker": "User-granted workspace permissions constrain available actions.",
        "evidence_urls": ["https://developers.notion.com/"],
        "confidence_score": 0.9,
        "notes": "Demo sample derived from the bundled research cache.",
    },
    "Stripe": {
        "one_line_description": "Payments infrastructure platform with highly structured APIs and strong developer onboarding.",
        "auth_methods": ["api_key"],
        "self_serve_status": "self_serve",
        "api_surface": "rest",
        "api_breadth": "broad",
        "existing_mcp": "unofficial",
        "buildability_verdict": "buildable_today",
        "main_blocker": "Sensitive financial actions still require careful scope design.",
        "evidence_urls": ["https://docs.stripe.com/api"],
        "confidence_score": 0.95,
        "notes": "Demo sample derived from the bundled research cache.",
    },
    "Otter AI": {
        "one_line_description": "AI meeting-notes platform with product-native automation potential and documented MCP positioning.",
        "auth_methods": ["oauth2", "mixed"],
        "self_serve_status": "partially_gated",
        "api_surface": "mixed",
        "api_breadth": "medium",
        "existing_mcp": "official",
        "buildability_verdict": "buildable_with_limitations",
        "main_blocker": "The platform surface appears narrower than older API-first collaboration tools.",
        "evidence_urls": ["https://help.otter.ai/"],
        "confidence_score": 0.71,
        "notes": "Demo sample derived from the bundled research cache.",
    },
}


COMMUNITY_MCP_APPS = {
    "Slack",
    "HubSpot",
    "Zendesk",
    "Shopify",
    "GitHub",
    "Notion",
    "Airtable",
    "Linear",
    "Jira",
    "Stripe",
    "Discord",
}


OFFICIAL_MCP_APPS = {"Otter AI", "Devin"}


def normalize_hint_url(value: str) -> str:
    cleaned = value.strip()
    if cleaned.startswith("http://") or cleaned.startswith("https://"):
        return cleaned
    return "https://" + cleaned.lstrip("/")


def build_default_evidence(app_name: str, website_hint: str) -> List[str]:
    urls = [normalize_hint_url(website_hint)]
    home = normalize_hint_url(website_hint.split("/")[0])
    if home not in urls:
        urls.append(home)
    return urls
